import React, { useState } from "react";
import Markdown from "react-markdown";
import { AnalysisResponse } from "../types";
import { RiskBadge } from "./RiskBadge";
import { Copy, Check, Download, Share2, ShieldAlert, Info } from "lucide-react";

interface AnalysisResultProps { response: AnalysisResponse; originalMessage: string; originalType: string; senderInfo?: string; }

export const AnalysisResult: React.FC<AnalysisResultProps> = ({ response, originalMessage, originalType, senderInfo }) => {
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);
  const [copiedSummary, setCopiedSummary] = useState(false);
  const handleCopyMarkdown = () => { navigator.clipboard.writeText(response.analysis); setCopiedMarkdown(true); setTimeout(() => setCopiedMarkdown(false), 2000); };
  const handleCopySummary = () => { navigator.clipboard.writeText(`--- PARECER DE SEGURANÇA SOC ---\nCase: ${response.caseId || "—"}\nTipo: ${originalType}\n${senderInfo ? `Remetente: ${senderInfo}\n` : ""}Risco: ${response.riskEmoji} ${response.riskLevel} (${response.riskScore ?? "—"}/100)\nConfiança: ${response.confidence ?? "—"}%\nData: ${new Date(response.timestamp).toLocaleString("pt-BR")}\n\n${response.analysis}`); setCopiedSummary(true); setTimeout(() => setCopiedSummary(false), 2000); };
  const handleDownloadReport = () => {
    const content = `=====================================================\n RELATÓRIO SOC - PHISHING & ENGENHARIA SOCIAL\n=====================================================\nCase: ${response.caseId || "—"}\nData/Hora: ${new Date(response.timestamp).toLocaleString("pt-BR")}\nTipo: ${originalType}\nRemetente: ${senderInfo || "Não especificado"}\nRisco: ${response.riskEmoji} ${response.riskLevel}\nRisk Score: ${response.riskScore ?? "—"}/100\nConfiança: ${response.confidence ?? "—"}%\nAção: ${response.recommendedAction || "—"}\nIncidente: ${response.incidentType || "—"}\nObjetivo: ${response.attackObjective || "—"}\n\nMENSAGEM ANALISADA:\n${originalMessage}\n\nPARECER TÉCNICO:\n${response.analysis}\n\n=====================================================\nFins educativos e preventivos.\n=====================================================`;
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `Relatorio_SOC_${response.caseId || new Date().toISOString().slice(0,10)}.txt`; link.click(); URL.revokeObjectURL(url);
  };

  return <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 sm:p-6 shadow-2xl space-y-6 animate-fade-in">
    <div className="p-4 sm:p-5 rounded-xl bg-slate-950/80 border border-slate-800 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
      <div className="flex items-center gap-3"><div className="p-2.5 bg-slate-900 border border-slate-700 rounded-xl"><ShieldAlert className="w-6 h-6 text-cyan-400" /></div><div><div className="flex items-center gap-2"><span className="text-xs font-mono uppercase tracking-wider text-slate-400">Resultado do Incidente SOC</span><span className="text-[10px] bg-slate-800 text-slate-300 font-mono px-2 py-0.5 rounded border border-slate-700">{response.caseId || "CASE-—"}</span></div><h3 className="text-base sm:text-lg font-bold text-white mt-0.5">Análise de Risco de Phishing</h3></div></div>
      <div className="flex items-center gap-3 self-stretch md:self-auto justify-between md:justify-end"><div className="text-right"><div className="text-2xl font-black text-cyan-300">{response.riskScore ?? "—"}<span className="text-xs text-slate-500">/100</span></div><div className="text-[10px] text-slate-500">confiança {response.confidence ?? "—"}%</div></div><RiskBadge level={response.riskLevel} emoji={response.riskEmoji} size="lg" /></div>
    </div>
    <div className="flex flex-wrap items-center gap-2 pt-1 pb-3 border-b border-slate-800/80"><button onClick={handleCopyMarkdown} className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-lg border border-slate-700 flex items-center gap-1.5">{copiedMarkdown ? <><Check className="w-3.5 h-3.5 text-emerald-400" /> Copiado!</> : <><Copy className="w-3.5 h-3.5 text-cyan-400" /> Copiar Markdown</>}</button><button onClick={handleCopySummary} className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-lg border border-slate-700 flex items-center gap-1.5">{copiedSummary ? <><Check className="w-3.5 h-3.5 text-emerald-400" /> Copiado!</> : <><Share2 className="w-3.5 h-3.5 text-cyan-400" /> Copiar Parecer</>}</button><button onClick={handleDownloadReport} className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-lg border border-slate-700 flex items-center gap-1.5"><Download className="w-3.5 h-3.5 text-cyan-400" /> Baixar Relatório</button></div>
    <div className="prose prose-invert max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-h1:text-base prose-h1:sm:text-lg prose-h1:text-cyan-400 prose-h1:border-b prose-h1:border-slate-800 prose-h1:pb-2 prose-h1:mt-6 prose-h1:mb-3 prose-p:text-slate-300 prose-p:text-xs prose-p:sm:text-sm prose-p:leading-relaxed prose-li:text-xs prose-li:sm:text-sm prose-li:text-slate-300 prose-strong:text-white prose-code:text-cyan-300 prose-code:bg-slate-950 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded"><Markdown>{response.analysis}</Markdown></div>
    <div className="p-4 bg-slate-950/90 border border-slate-800 rounded-xl flex items-start gap-3 text-xs text-slate-400"><Info className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" /><div><p className="font-semibold text-slate-300">Aviso do Analista SOC:</p><p className="mt-0.5">A avaliação é baseada somente nas evidências fornecidas e tem finalidade educativa. Confirme suspeitas usando canais oficiais e independentes.</p></div></div>
  </div>;
};
