import React, { useState } from "react";
import { CheckCircle2, Trophy, XCircle } from "lucide-react";
const scenarios = [
 {title:"Atualização urgente",text:"Seu acesso será suspenso em 30 minutos. Confirme sua senha no link abaixo.",options:["Phishing + Credential Harvesting","Baiting","Vishing","Nenhum risco"],correct:0,explanation:"Urgência, ameaça de bloqueio e pedido de senha são fortes sinais de engenharia social."},
 {title:"Documento financeiro inesperado",text:"Segue o documento solicitado. Abra o anexo para consultar o pagamento.",options:["Spearphishing Attachment","Quishing","Smishing","Nenhum risco"],correct:0,explanation:"Anexos inesperados devem ser validados por canal independente antes de serem abertos."},
 {title:"QR Code promocional",text:"Escaneie o QR Code para resgatar sua recompensa e confirme seus dados.",options:["Quishing + coleta de dados","Vishing","BEC","Nenhum risco"],correct:0,explanation:"QR Codes podem levar a páginas falsas; valide o destino antes de prosseguir."}
];
export function SOCTrainingModal({isOpen,onClose}:{isOpen:boolean;onClose:()=>void}){
 const [index,setIndex]=useState(0),[selected,setSelected]=useState<number|null>(null),[score,setScore]=useState(0),[done,setDone]=useState(false); if(!isOpen)return null; const s=scenarios[index];
 const answer=()=>{if(selected===null)return;if(selected===s.correct)setScore(v=>v+1);if(index===scenarios.length-1)setDone(true);else{setIndex(v=>v+1);setSelected(null)}}; const reset=()=>{setIndex(0);setSelected(null);setScore(0);setDone(false)};
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-2xl rounded-2xl border border-slate-700 bg-slate-950 p-6 shadow-2xl"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Trophy className="h-5 w-5 text-yellow-400"/><h2 className="font-bold text-white">SOC Training Mode</h2></div><button onClick={onClose} className="text-slate-500">✕</button></div>{done?<div className="py-10 text-center"><div className="text-4xl font-black text-white">{score}/{scenarios.length}</div><p className="mt-2 text-slate-400">Pontuação do treinamento</p><button onClick={reset} className="mt-6 rounded-xl bg-cyan-500 px-4 py-2 text-sm font-bold text-slate-950">Refazer</button></div>:<><div className="mt-6 text-xs text-cyan-400">CASO {index+1} DE {scenarios.length}</div><h3 className="mt-2 text-xl font-bold text-white">{s.title}</h3><div className="mt-4 rounded-xl border border-slate-800 bg-slate-900 p-4 text-sm text-slate-300">{s.text}</div><div className="mt-4 space-y-2">{s.options.map((o,i)=><button key={o} onClick={()=>setSelected(i)} className={`w-full rounded-xl border p-3 text-left text-sm ${selected===i?"border-cyan-500 bg-cyan-950/40 text-cyan-200":"border-slate-800 bg-slate-900/50 text-slate-300"}`}>{o}</button>)}</div>{selected!==null&&<div className="mt-4 flex gap-2 rounded-xl bg-slate-900 p-3 text-xs text-slate-400">{selected===s.correct?<CheckCircle2 className="h-4 w-4 text-emerald-400"/>:<XCircle className="h-4 w-4 text-red-400"/>}{s.explanation}</div>}<button disabled={selected===null} onClick={answer} className="mt-5 w-full rounded-xl bg-cyan-500 py-3 text-sm font-bold text-slate-950 disabled:opacity-40">{index===scenarios.length-1?"Finalizar":"Responder e continuar"}</button></>}</div></div>;
}